### PR TITLE
Eventbus ts definitions

### PR DESCRIPTION
**Pull request by oddeirik**
I've added some _very_ simple Typescript definitions for vertx-eventbus-js, ref issue #61.

I have no idea if this is the best way or even correct way of doing it. I'm still trying to grasp exports, modules, namespaces, interfaces and classes for Typescript... 

In any case these definitions should provide auto-completion for some of the methods, like send, publish, etc. I'm sure it could be improved with further type checking of properties, callback signatures, and so on, but that requires more knowledge of Typescript than I currently have 😉 

I've also updated the sockjs-client dependency to use the latest 1.x version available.

### CODE REVIEW

**Comment by pmlopes** [comment]
@oddeirik the `headers` parameter in the method definitions are optional, i'm not sure if the `ts` reflect that. Also the `callback` on `send` is also optional.

**Comment by oddeirik** [comment]
Good catch!

The problem with the header being an optional argument is that there can't be any required arguments following an optional one. In vertx-eventbus.js there is a check to see if the headers are in fact a function  and it just uses that as the callback instead. I'm not sure how to reflect that in the Typescript definitions, to be honest.

I'll add a commit for the send callback and I can make the header parameter for publish optional at least.

**Comment by oddeirik** [comment]
Just an update: I've now added these definitions as a PR to the DefinitelyTyped repository, hopefully that'll get merged. If that goes well, I can close this PR. Perhaps having it in DT can make contributions easier as well, as I'm sure there is room for improvement in the definitions I've provided 😃

**Comment by pmlopes** [comment]
@oddeirik can you link the PR to this issue and btw how did you work out the optional parameters?

**Comment by oddeirik** [comment]
Sorry, meant to include the link to the PR in the previous post: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16521.

As for the optional headers, I've not done anything with that, as the current definitions works well enough for my use at the moment. The callback on send is optional, however.

**Comment by oddeirik** [comment]
The DefinitelyTyped PR just merged, so I'll close this one.

**Pull request closed without merging**
